@API_HostAddress = http://localhost:5016

GET {{API_HostAddress}}/openapi/v1.json

###

### Listar Todos os Clientes
GET https://localhost:7170/api/clients

### 

### Criar Cliente
POST {{API_HostAddress}}/api/client
Content-Type: application/json
Accept: application/json

{
  "name": "Bob teste",
  "cpf": "12345678901",
  "email": "teste@teste.com",
  "phone": "11 11111-1111",
  "gender": 0
}
###